### ISSUE TITLE
Flow errors

### ISSUE THREAD

**Issue by iegik** [APSL/react-native-keyboard-aware-scroll-view#117]
```
node_modules/react-native-keyboard-aware-scroll-view/lib/KeyboardAwareListView.js:37
 37:           this.props.onScroll && this.props.onScroll(e)
                                      ^^^^^^^^^^^^^^^^^^^^^^ call of method `onScroll`. Function cannot be called on
 37:           this.props.onScroll && this.props.onScroll(e)
                                      ^^^^^^^^^^^^^^^^^^^^^^ property `onScroll` of unknown type

node_modules/react-native-keyboard-aware-scroll-view/lib/KeyboardAwareMixin.js:133
133:   handleOnScroll: function (e) {
                                 ^ parameter `e`. Missing annotation

```

**Comment by Palisand** [comment]
I'm getting more issues than above.
`flow-bin` 0.42.0
`react-native` 0.44.0
`react-native-keyboard-aware-scroll-view` 0.2.9

**Comment by Swordsman-Inaction** [comment]
I'm not familiar with flow. Anyone wants to make a PR for this?

**Comment by alvaromb** [comment]
Hi!

Can you help us with Flow errors sending us a PR? We've fixed a bunch of them in the latest release, but we may have some errors left...

https://github.com/APSL/react-native-keyboard-aware-scroll-view/releases/tag/v0.3.0

**Comment by Palisand** [comment]
@alvaromb @Swordsman-Inaction Sure.

**Comment by Palisand** [comment]
@alvaromb @Swordsman-Inaction I do not know how to fix the prop-type-related flow errors I am getting now unless I refactor the components so that they do not use `createReactClass` (which means updating to ES6). This would involve a lot of changes (including converting the mixin to an HOC) that I wouldn't mind tackling. Would you accept this sort of PR?

**Comment by alvaromb** [comment]
@Palisand sure!

Moving to HOC is something I had on my mind for quite a long time, but due to the mobile team activity I wasn't able to do it yet.

I would gladly help you and review a PR of this kind 😉

**Comment by Palisand** [comment]
@alvaromb It has been a while but I haven't forgotten about this. With the recent release of flow 0.53.0, there is now much better support for higher order components. However, it's still not quite there yet. As far as I can tell, there is no proper way to flow-type a `keyboardAware` hoc that both **injects and passes** props (but I might be able to find an inject-only alternative). Moreover, there is a fix still in the works for a [bug](https://github.com/facebook/flow/issues/4709) with es6 exports.
