### ISSUE TITLE
responder.scrollResponderScrollTo is not a function

### ISSUE THREAD

**Issue by luutruong** [APSL/react-native-keyboard-aware-scroll-view#504]
Today i have upgraded to RN 0.65.1 and got this error.

```
TypeError: responder.scrollResponderScrollTo is not a function. (In 'responder.scrollResponderScrollTo({
            x: x,
            y: y,
            animated: animated
          })', 'responder.scrollResponderScrollTo' is undefined)
```

Lib version: `"react-native-keyboard-aware-scroll-view": "^0.9.4",`

The error pointed to this line: https://github.com/APSL/react-native-keyboard-aware-scroll-view/blob/master/lib/KeyboardAwareHOC.js#L276

**Comment by luutruong** [comment]
PR fix: https://github.com/APSL/react-native-keyboard-aware-scroll-view/pull/501

**Comment by luutruong** [comment]
Related issue: https://github.com/APSL/react-native-keyboard-aware-scroll-view/issues/494

**Comment by codler** [comment]
I have [forked](https://github.com/codler/react-native-keyboard-aware-scroll-view) the repo to fix this issue.
```
npm i @codler/react-native-keyboard-aware-scroll-view

**Comment by hemantasapkota** [comment]
Brilliant, thanks @codler

**Comment by dongdyang** [comment]
try this one: `    "react-native-keyboard-aware-scroll-view": "github:APSL/react-native-keyboard-aware-scroll-view#pull/501/head",
`

**Comment by FadiAboMsalam** [comment]
the issue persist in RN66.3

**Comment by DanielAraldi** [comment]
> the issue persist in RN66.3

On RN 66.3 I added the following dependency in the `package.json` of my project and it worked:

```json
"resolutions": {
  "native-base/@codler/react-native-keyboard-aware-scroll-view": "2.0.0"
},
```

**Note**: I am using `native-base`.

**Comment by masudhossain** [comment]
Issue is persistent in RN68

**Comment by Yandamuri** [comment]
Issue resolved with latest version `react-native-keyboard-aware-scroll-view: 0.9.5`

**Comment by jordzawada** [comment]
I am getting this issue on RN 68, but I am not using "react-native-keyboard-aware-scroll-view: 0.9.5" in this particular screen. It does happen when I dismiss a keyboard in a modals TextInput.

**Comment by harshmdr** [comment]
Facing issue with RN 68 and native base.

**Comment by Aryk** [comment]
Im on 0.9.5 and still experiencing this issue occasionally, specifically after a sandbox purchase is made.

**Comment by miteshdb** [comment]
It is happening on RN 71 as well, using native-base

**Comment by miteshdb** [comment]
`overrides` worked for me on RN 71, put it in package.json
_I was using `native-base`, maybe it won't work for one's who is using keyboard aware package directly_

```
"overrides": {
    "native-base": {
      "@codler/react-native-keyboard-aware-scroll-view": "2.0.1"
    }
  }
```

removed `node_modules` and re-installed packages using `npm install`, and crash went away

**Comment by davidwinograd1** [comment]
None of these worked for me. I am using RN 0.68.7 and "react-native-keyboard-aware-scroll-view": "^0.9.5". Can someone help / was anyone able to fix it? @miteshdb @luutruong @codler @dongdyang

**Comment by luutruong** [comment]
> None of these worked for me. I am using RN 0.68.7 and "react-native-keyboard-aware-scroll-view": "^0.9.5". Can someone help / was anyone able to fix it? @miteshdb @luutruong @codler @dongdyang

Did you try to clear cache?

**Comment by alishah514** [comment]
Update the following code in the /node_modules/@codler/react-native-keyboard-aware-scroll-view/lib/KeyboardAwareHOC.js file line number 244.

`scrollToPosition = (x: number, y: number, animated: boolean = true) => {
  const responder = this.getScrollResponder()
  if (!responder) {
    return
  }
  if (responder.scrollResponderScrollTo) {
    // React Native < 0.65
    responder.scrollResponderScrollTo({ x, y, animated })
  } else if (responder.scrollTo) {
    // React Native >= 0.65
    responder.scrollTo({ x, y, animated })
  }
  // responder && responder.scrollResponderScrollTo({ x, y, animated })
}

scrollToEnd = (animated?: boolean = true) => {
  const responder = this.getScrollResponder()
  if (!responder) {
    return
  }
  if (responder.scrollResponderScrollTo) {
    // React Native < 0.65
    responder.scrollResponderScrollTo({ x, y, animated })
  } else if (responder.scrollTo) {
    // React Native >= 0.65
    responder.scrollTo({ x, y, animated })
  }
  // responder && responder.scrollResponderScrollToEnd({ animated })
}`

Above Worked for me! I was using older version of native-base "^2.15.2" with latest react native version "0.72.6". I don't know where that codler came from but this solved my issue.

**Comment by Seunope** [comment]
scrollToPosition = (x: number, y: number, animated: boolean = true) => {
        const responder = this.getScrollResponder()
        if (!responder) {
          return
        }
        if (responder.scrollResponderScrollTo) {
          // React Native < 0.65
          responder.scrollResponderScrollTo({ x, y, animated })
          } else if (responder.scrollTo) {
          // React Native >= 0.65
          responder.scrollTo({ x, y, animated })
          }
          // responder && responder.scrollResponderScrollTo({ x, y, animated })
        }
      
        scrollToEnd = (animated?: boolean = true) => {
        const responder = this.getScrollResponder()
        if (!responder) {
         return
        }
        if (responder.scrollResponderScrollTo) {
          // React Native < 0.65
          responder.scrollResponderScrollTo({ x, y, animated })
          } else if (responder.scrollTo) {
          // React Native >= 0.65
          responder.scrollTo({ x, y, animated })
        }
        // responder && responder.scrollResponderScrollToEnd({ animated })
    }


@alishah514 solution worked.  I arranged the text for proper visualization. I am using  native-base: 2.13.15,  react-native: 0.72.6

**Comment by Yandamuri** [comment]
@Seunope @alishah514 This issue occurs only if we are using native base?

**Comment by alishah514** [comment]
@Yandamuri Yes, if you look into native base's inner node modules you'll find dependency of codler/react-native-keyboard-aware-scroll-view there. That is the main reason of this issue. Plus Older Version of native base and newer react native version makes this issue.

**Comment by yarelosa** [comment]
> ```
>  scrollToPosition = (x: number, y: number, animated: boolean = true) => {
>     const responder = this.getScrollResponder()
>     if (!responder) {
>       return
>     }
>     if (responder.scrollResponderScrollTo) {
>       // React Native < 0.65
>       responder.scrollResponderScrollTo({ x, y, animated })
>       } else if (responder.scrollTo) {
>       // React Native >= 0.65
>       responder.scrollTo({ x, y, animated })
>       }
>       // responder && responder.scrollResponderScrollTo({ x, y, animated })
>     }
>   
>     scrollToEnd = (animated?: boolean = true) => {
>     const responder = this.getScrollResponder()
>     if (!responder) {
>      return
>     }
>     if (responder.scrollResponderScrollTo) {
>       // React Native < 0.65
>       responder.scrollResponderScrollTo({ x, y, animated })
>       } else if (responder.scrollTo) {
>       // React Native >= 0.65
>       responder.scrollTo({ x, y, animated })
>     }
>     // responder && responder.scrollResponderScrollToEnd({ animated })
> }
> ```
> 
> @alishah514 solution worked. I arranged the text for proper visualization. I am using native-base: 2.13.15, react-native: 0.72.6

Are you tried to apply an patch?

**Comment by patlux** [comment]
When using `yarn` just pin the latest version in your `package.json` to fix the error:

```json
  "resolutions": {
    "@codler/react-native-keyboard-aware-scroll-view": "2.0.1"
  }
```

**Comment by ShamuXX** [comment]
> `overrides` worked for me on RN 71, put it in package.json _I was using `native-base`, maybe it won't work for one's who is using keyboard aware package directly_
> 
> ```
> "overrides": {
>     "native-base": {
>       "@codler/react-native-keyboard-aware-scroll-view": "2.0.1"
>     }
>   }
> ```
> 
> removed `node_modules` and re-installed packages using `npm install`, and crash went away

This worked for me on "react-native": "^0.74.2", the error is given by the path
/node_modules/@codler/react-native-keyboard-aware-scroll-view/lib/KeyboardAwareHOC.js

Thanks a lot, I tried everything and only this configuration works. :D
